[app]
name = "mpaas"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8080"

[app.grpc]
host = "127.0.0.1"
port = "18080"

[keyauth]
host = "127.0.0.1"
port = "18050"
client_id = "tNMEYe5aCSZpb78TCYzrx0SD"
client_secret = "NlaVX6xsGVzqbxlLOSKXx3ARxOjls5VR"

[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "mpaas"
password = "123456"
database = "mpaas"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"